### ISSUE TITLE
Add User Agent config key

### ISSUE THREAD

**Issue by mvollrath** [EndPointCorp/com.endpoint.lg.browser.static#1]
We need to be able to override the browser's User Agent.  Setting it to an iOS device gives us free multi-touch in Maps API.

Add config key: `lg.browser.userAgent` defaulting to empty string.

Override with Chrome flag: `--user-agent=AGENT`.

If the config key is not set, the `--user-agent` flag should not be appended, using the true agent.

**Comment by jonjensen** [comment]
Matt V. and Kiel don't think this is the best way to implement this and are discussing alternatives.

**Comment by mvollrath** [comment]
This is not a bad way to get what we want, but let's discuss the problem so that we're all on the same page.

There are things we want to customize about specific instances of Chrome.  Some of these things can be achieved with command line flags.  Some of them can be achieved in extension code.  There is some overlap between things we can achieve with command line flags and extension code.

The first use case is that want to use a different UserAgent for a Maps API map because it adds multi-touch for free.

Setting the UserAgent for a browser instance vs. overriding it through the webRequest API of an extension are comparable but not equivalent solutions.

Once the UserAgent is set for a browser instance, it will be used for all content retrieved by that instance.  There are potential side effects to this when using public content (as evidenced by Maps API).  This is the solution described in this issue.  It should be mentioned that this feature is only a convenience, because all you have to do to change the UserAgent is append a flag to IS's default browser args in a live activity config.

If the UserAgent is overridden by a webRequest handler in an extension, it will affect specific url patterns in any browser loading that extension.  In the case of Maps API, we may not want the UserAgent to be overridden on the Street View pano display browsers, because the side effects are unknown.

A relatively lightweight solution would be to always load an extension with a hardcoded webRequest handler specifically for the Maps API.

The heaviest and most flexible solution for setting the UserAgent exactly where we want would be generating configuration for an unpacked extension loaded by the browser launcher with mappings of url pattern to agent.  This is the only way to modify the UserAgent exactly where we want it and nowhere else.

I'm always in favor of adding features over hacks, so I'd just add this simple feature, lay the groundwork for further command line arg configuration, and roll on.  When we need functionality that absolutely requires an extension let's do it.

**Comment by mvollrath** [comment]
As @eggyknap says in https://github.com/EndPointCorp/com.endpoint.lg.browser.service/issues/1 this should be done in the browser service static_page, i.e. `lg.browser.static_page.touchscreen.user_agent`

**Comment by mvollrath** [comment]
We decided not to add this feature yet.
